name: Test on PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm ci
        cd lambda-adapters/weather
        npm install
        cd ..
        cd album
        npm install
        cd ..

    - name: Run tests
      run: npm test
